### ISSUE TITLE
Quick Sort in Java

### ISSUE THREAD

**Issue by yuvithakur007** [pawiie/DSA#7]
@pawiie I want to work on this issue, Please assign it to me.

**Comment by yuvithakur007** [comment]
sir, after assigning why closed this issue?

**Comment by pawiie** [comment]
ok I am reopening it, now you can work on it.

**Comment by yuvithakur007** [comment]
> ok I am reopening it, now you can work on it.

sorry for misunderstanding, I though you will assign me this issue first, then I have to start work on it. I am a newbie, I don't know much about this. But now, I get it. Thank you for assigning me this issue sir.
